#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle start up script
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions "$var", "${var.word}", "${var,}", "${var^}", "${var##pattern}", "${var%%pattern}";
#         * compound commands having a finally clause, i.e. "{ f || true; } && g
#         * and sequences of commands connected by && or ||;
#         * notably NOT command substitution using backticks and not using $() syntax;
#
#   (2) Want to use Gradle as mentioned in the FAQ (<https://gradle.org/faq#configure_gradle_for_using_behind_a_proxy>) when using Gradle behind a proxy,
#       you can use the following options on the command line (notice the double dash):
#
#           ./gradlew ... --system-prop http.proxyHost=myProxyHost --system-prop http.proxyPort=myProxyPort
#
#   (3) JVM maximum heap size: by default the script will choose the maximum heap
#       size it can based on system memory. You can override this by setting the
#       environment variable GRADLE_OPT to "-Xmx1024m" or similar. If you're
#       behind a corporate proxy, you might want to force the use of an
#       HTTP proxy: -Dhttp.proxyHost=myProxyHost -Dhttp.proxyPort=8080
#
#   (4) When using the Gradle wrapper, you will automatically get new Gradle
#       releases when it is time to upgrade. Typically via a HTTPS connection.
#       This could fail behind a HTTPS intercepting corporate proxy. The HTTP
#       client at the core of Gradle will support the system properties
#       -Dhttp.proxyHost and -Dhttp.proxyPort for proxy configuration. If your
#       corporate IT department does not allow direct access to the sources, you
#       can declare an HTTP proxy as follows:
#
#           ./gradlew -Dhttp.proxyHost=myProxyHost -Dhttp.proxyPort=8080
#
#   About the wrapper executable:
#
#       The gradle wrapper (code) is signature-proof to prevent tampering.
#       However, just like downloading software via the internet, downloading
#       through the gradle wrapper does involve a commit of sort because
#       Gradle software, from gradle plugins included, may be considered as
#       dependencies. As such, have the freedom to either use the wrapper or
#       to manually download and setup Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
	ls=$( ls -ld "$app_path" )
	link=${ls#*' -> '}	# remove leading tab and everything up to ->
	case $link in             #(
	  /*)   app_path=$link ;; #(
	  *)    app_path=$APP_HOME$link ;;
	esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="$(ls "$APP_HOME"/gradle/wrapper/gradle-wrapper.jar | head -1)"
if [ -z "$APP_JAR" ]; then
    echo "Not found: $APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    exit 1
fi
CLASSPATH=$APP_JAR

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD=java
    command -v java >/dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2; exit 1; }
fi

# Increase the maximum file descriptors if we can, though its usually unnecessary on most systems.
max_fd=$( ulimit -H -n ) ||
    max_fd=65536
{ ulimit -n $max_fd; } 2>/dev/null || :

# For Darwin, add options to specify how the application appears in the dock, menus, etc.
darwin=false
case $( uname ) in                        #(
  Darwin* )   darwin=true   ;; #(
  * )         darwin=false  ;;
esac

if $darwin; then
    # Now we have the real java command, which is necessary to both
    # create the runnable jar and collect the resulting diagnostics.
    JAVA_OPTS="$JAVA_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if false; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$( find -L / -maxdepth 3 -type d -name sources 2>/dev/null )
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGWIN_MODULE" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGWIN_MODULE)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=$( echo "$arg"|egrep -c "$OURCYGPATTERN" ) -o 0
        CHECK2=$( echo "$arg"|egrep -c "^-"  ) -o 0
        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then             #(
            arg=$( cygpath --path --unix "$arg" )
        fi                                                      #(
        if [ $i -lt $((($#+1)/2)) ] ; then                    #(
            arg="\"$arg\""
        fi                                                     #(
        ARG_STRING="$ARG_STRING $arg"
        i=$((i+1))
    done
    # if @directory arg, first argument is which has the most files, then that is the input dir
    if [ "$1" = "@" ] ; then
        SOURCE_FILES_FOUND=$( find -L . -type f -name "*.gradle*" | head -1 )
        $JAVACMD -Xmx64m "$@" -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$ARG_STRING"
    else
        /bin/sh -c "\"$JAVACMD\" $JAVA_OPTS \
        \"-Dorg.gradle.appname=$APP_BASE_NAME\" \
        -classpath \"$CLASSPATH\" \
        org.gradle.wrapper.GradleWrapperMain \
        \"$@\""
    fi
else
    exec "$JAVACMD" $JAVA_OPTS \
        -Dorg.gradle.appname=$APP_BASE_NAME \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
fi
